import type { ExplorerJob } from "./types";

export const MOCK_JOBS: ExplorerJob[] = [
  {
    id: "1",
    title: "AI数据工程师",
    company: "星火电子",
    salary: "15k-25k",
    city: "深圳·福田区",
    experience: "2年及以上",
    education: "本科",
    companySize: "100-499人",
    platform: "51job",
    score: 0,
  },
  {
    id: "2",
    title: "电商数字营销运营",
    company: "乐悦品牌",
    salary: "12k-18k·13薪",
    city: "深圳·南山区",
    experience: "3年及以上",
    education: "本科",
    companySize: "500人以上",
    platform: "BOSS直聘",
    score: 0,
  },
  {
    id: "3",
    title: "大模型应用产品经理",
    company: "云智科技",
    salary: "25k-35k",
    city: "深圳·宝安区",
    experience: "5年及以上",
    education: "硕士",
    companySize: "100-499人",
    platform: "猎聘",
    score: 0,
  },
  {
    id: "4",
    title: "后端开发工程师",
    company: "某互联网",
    salary: "18k-28k",
    city: "深圳·龙岗区",
    experience: "无需经验",
    education: "本科",
    companySize: "20-99人",
    platform: "BOSS直聘",
    score: 0,
  },
  {
    id: "5",
    title: "数据分析师",
    company: "数联医疗",
    salary: "14k-22k",
    city: "深圳·罗湖区",
    experience: "1年及以上",
    education: "本科",
    companySize: "20-99人",
    platform: "51job",
    score: 0,
  },
  {
    id: "6",
    title: "算法工程师",
    company: "智算未来",
    salary: "30k-45k",
    city: "深圳·福田区",
    experience: "3年及以上",
    education: "硕士",
    companySize: "500人以上",
    platform: "猎聘",
    score: 0,
  },
  {
    id: "7",
    title: "前端开发工程师",
    company: "轻舟互联",
    salary: "16k-26k",
    city: "深圳·龙华区",
    experience: "2年及以上",
    education: "本科",
    companySize: "100-499人",
    platform: "BOSS直聘",
    score: 0,
  },
];
